// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4BinConcurrent_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4BinExternal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4BinHybrid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ContConcurrent_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ContExternal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ContHybrid_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4T2EConcurrent_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4T2EConcurrentC0_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4T2EExternal_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4T2EHybrid_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4BinConcurrent_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BinConcurrent_mod, 0},
    {"_rcpp_module_boot_stan_fit4BinExternal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BinExternal_mod, 0},
    {"_rcpp_module_boot_stan_fit4BinHybrid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BinHybrid_mod, 0},
    {"_rcpp_module_boot_stan_fit4ContConcurrent_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ContConcurrent_mod, 0},
    {"_rcpp_module_boot_stan_fit4ContExternal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ContExternal_mod, 0},
    {"_rcpp_module_boot_stan_fit4ContHybrid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ContHybrid_mod, 0},
    {"_rcpp_module_boot_stan_fit4T2EConcurrent_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4T2EConcurrent_mod, 0},
    {"_rcpp_module_boot_stan_fit4T2EConcurrentC0_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4T2EConcurrentC0_mod, 0},
    {"_rcpp_module_boot_stan_fit4T2EExternal_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4T2EExternal_mod, 0},
    {"_rcpp_module_boot_stan_fit4T2EHybrid_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4T2EHybrid_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_iaborrow(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
